# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Boilerplate

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:

  check:
    name: Boilerplate Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        extension:
        - go
        - sh
        - yaml

        # Map between extension and human-readable name.
        include:
        - extension: go
          language: Go
        - extension: sh
          language: Bash
        - extension: yaml
          language: YAML

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: chainguard-dev/actions/boilerplate@9d631658f55713e5f63ca0cc21ee168f81301fd9 # v1.6.30
        with:
          extension: ${{ matrix.extension }}
          language: ${{ matrix.language }}
