# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Do Not Submit

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Do Not Submit
        uses: chainguard-dev/actions/donotsubmit@5f020827ba80ff5d64d45116542d0c733e8e7e71 # v1.6.23
