# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Do Not Submit

on:
  pull_request:
    branches:
      - 'main'

permissions: {}

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Do Not Submit
        uses: chainguard-dev/actions/donotsubmit@4d37df0d85a91f619edc34a8803323033cdcb124 # v1.6.27
