# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Do Not Submit

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

permissions: {}

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Do Not Submit
        uses: chainguard-dev/actions/donotsubmit@main
