# Copyright 2022 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Verify

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

permissions: {}

jobs:

  verify:
    name: Verify Codegen
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      GOPATH: ${{ github.workspace }}

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
      with:
        egress-policy: audit

    - name: Check out code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: ./src/github.com/${{ github.repository }}
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version-file: './src/github.com/${{ github.repository }}/go.mod'
        check-latest: true

    # https://github.com/mvdan/github-actions-golang#how-do-i-set-up-caching-between-builds
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        # In order:
        # * Module download cache
        # * Build cache (Linux)
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Update Codegen
      shell: bash
      working-directory: ./src/github.com/${{ github.repository }}
      run: |
        ./hack/update-codegen.sh

    - name: Verify
      uses: chainguard-dev/actions/nodiff@8bb24c24be6871bee44f19be55ea11e3b2aea3dd # main
      with:
        path: ./src/github.com/${{ github.repository }}
        fixup-command: "./hack/update-codegen.sh"
